//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__LayoutAdmin_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__LayoutAdmin_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Areas\Admin\Views\Shared\_LayoutAdmin.cshtml"
       var u = Session["use"] as Ictshop.Models.Nguoidung; 

#line default
#line hidden

#line 2 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Areas\Admin\Views\Shared\_LayoutAdmin.cshtml"
       __o = Html.ActionLink("ICT SHOP", "Index", "Home", new { @class = "menu1" });


#line default
#line hidden

#line 3 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Areas\Admin\Views\Shared\_LayoutAdmin.cshtml"
                                                                 __o = Url.Action("Details", "Nguoidungs", new { id = u.MaNguoiDung  });


#line default
#line hidden

#line 4 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Areas\Admin\Views\Shared\_LayoutAdmin.cshtml"
                                                                                                                                                __o = u.Email;


#line default
#line hidden

#line 5 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Areas\Admin\Views\Shared\_LayoutAdmin.cshtml"
                       __o = Html.ActionLink("Sản phẩm", "Index", "Home", null, new { @style = "color:white;" });


#line default
#line hidden

#line 6 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Areas\Admin\Views\Shared\_LayoutAdmin.cshtml"
                       __o = Html.ActionLink("Hãng sản xuất", "Index", "Hangsanxuats", null, new { @style = "color:white;" });


#line default
#line hidden

#line 7 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Areas\Admin\Views\Shared\_LayoutAdmin.cshtml"
                       __o = Html.ActionLink("Hệ điều hành", "Index", "Hedieuhanhs", null, new { @style = "color:white;" });


#line default
#line hidden

#line 8 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Areas\Admin\Views\Shared\_LayoutAdmin.cshtml"
                       __o = Html.ActionLink("Người dùng", "Index", "Nguoidungs", null, new { @style = "color:white;" });


#line default
#line hidden

#line 9 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Areas\Admin\Views\Shared\_LayoutAdmin.cshtml"
                       __o = Html.ActionLink("Phân quyền", "Index", "Phanquyens", null, new { @style = "color:white;" });


#line default
#line hidden

#line 10 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Areas\Admin\Views\Shared\_LayoutAdmin.cshtml"
                       __o = Html.ActionLink("Đơn hàng", "Index", "Donhangs", null, new { @style = "color:white;" });


#line default
#line hidden

#line 11 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Areas\Admin\Views\Shared\_LayoutAdmin.cshtml"
                       __o = Html.ActionLink("Thống kê", "Index", "Thongkes", null, new { @style = "color:white;" });


#line default
#line hidden

#line 12 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Areas\Admin\Views\Shared\_LayoutAdmin.cshtml"
               __o = RenderBody();


#line default
#line hidden
}
}
}
