//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

#line 2 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Areas\Admin\Views\Home\Index.cshtml"
using PagedList.Mvc;

#line default
#line hidden

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Areas\Admin\Views\Home\Index.cshtml"
__o = model;


#line default
#line hidden

#line 3 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Areas\Admin\Views\Home\Index.cshtml"
      
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    

#line default
#line hidden

#line 4 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Areas\Admin\Views\Home\Index.cshtml"
                               __o = Html.ActionLink("Thêm sản phẩm mới", "Create");


#line default
#line hidden

#line 5 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Areas\Admin\Views\Home\Index.cshtml"
        foreach (var item in Model)
    {
        

#line default
#line hidden

#line 6 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Areas\Admin\Views\Home\Index.cshtml"
           __o = Html.DisplayFor(modelItem => item.Tensp);


#line default
#line hidden

#line 7 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Areas\Admin\Views\Home\Index.cshtml"
           __o = String.Format("{0:0,0}", item.Giatien);


#line default
#line hidden

#line 8 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Areas\Admin\Views\Home\Index.cshtml"
           __o = Html.DisplayFor(modelItem => item.Soluong);


#line default
#line hidden

#line 9 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Areas\Admin\Views\Home\Index.cshtml"
           __o = Html.DisplayFor(modelItem => item.Mota);


#line default
#line hidden

#line 10 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Areas\Admin\Views\Home\Index.cshtml"
           __o = Html.DisplayFor(modelItem => item.Thesim);


#line default
#line hidden

#line 11 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Areas\Admin\Views\Home\Index.cshtml"
                     __o = Url.Content("~" +item.Anhbia);


#line default
#line hidden

#line 12 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Areas\Admin\Views\Home\Index.cshtml"
           __o = Html.DisplayFor(modelItem => item.Hangsanxuat.Tenhang);


#line default
#line hidden

#line 13 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Areas\Admin\Views\Home\Index.cshtml"
           __o = Html.DisplayFor(modelItem => item.Hedieuhanh.Tenhdh);


#line default
#line hidden

#line 14 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Areas\Admin\Views\Home\Index.cshtml"
               __o = Html.ActionLink("Sửa", "Edit", new { id = item.Masp }, new { @style = "color:white;" });


#line default
#line hidden

#line 15 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Areas\Admin\Views\Home\Index.cshtml"
               __o = Html.ActionLink("Chi tiết", "Details", new { id = item.Masp }, new { @style = "color:white;" });


#line default
#line hidden

#line 16 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Areas\Admin\Views\Home\Index.cshtml"
               __o = Html.ActionLink("Xóa", "Delete", new { id = item.Masp }, new { @style = "color:white;" });


#line default
#line hidden

#line 17 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Areas\Admin\Views\Home\Index.cshtml"
             
    }

#line default
#line hidden

#line 18 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Areas\Admin\Views\Home\Index.cshtml"
      __o = Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber;


#line default
#line hidden

#line 19 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Areas\Admin\Views\Home\Index.cshtml"
                                                                    __o = Model.PageCount;


#line default
#line hidden

#line 20 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Areas\Admin\Views\Home\Index.cshtml"
__o = Html.PagedListPager(Model, page => Url.Action("Index",
        new { page }));


#line default
#line hidden
}
}
}
