//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

#line 4 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Views\Shared\_Layout.cshtml"
using Ictshop.Models;

#line default
#line hidden

public class _Page__Layout_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__Layout_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Views\Shared\_Layout.cshtml"
      __o = ViewBag.Title;


#line default
#line hidden

#line 2 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Views\Shared\_Layout.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 3 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Views\Shared\_Layout.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 5 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Views\Shared\_Layout.cshtml"
       var u = Session["use"] as Ictshop.Models.Nguoidung; 

#line default
#line hidden

#line 6 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Views\Shared\_Layout.cshtml"
                __o = Url.Action("Test", "User");


#line default
#line hidden

#line 7 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Views\Shared\_Layout.cshtml"
           __o = Html.Action("GioHangPartial", "GioHang", new { @class = "giohabg" });


#line default
#line hidden

#line 8 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Views\Shared\_Layout.cshtml"
   __o = RenderBody();


#line default
#line hidden

#line 9 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Views\Shared\_Layout.cshtml"
__o = ScriptsYRender("~/bundles/jquery")1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Views\Shared\_Layout.cshtml"
__o = Scripts.Render("~/bundles/jquery");


#line default
#line hidden

#line 11 "C:\Users\Admin\AppData\Locbootstrapp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Views\Shared\_Layout.cshtml"
__o = Scripts.Render("~/bundles/bootstrap");


#line default
#line hidden

#
}
}
}
