//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Views\Home\Index.cshtml"
      
    ViewBag.Title = "ICT SHOP";
    


#line default
#line hidden

#line 2 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Views\Home\Index.cshtml"
__o = Html.Action("DanhmucPartial", "Danhmuc")Html.Action("dtsamsungpartial", "Sanpham");


#line default
#line hidden

#line 3 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\ViedtiphonePartialcshtSanphamo = Html.Action("DanhmucPartial", "Danhmuc");


#line default
#line hidden

#line 4 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Viedtsamsungpartialshtml"
__o = Html.Action("dtiphonePartial", "Sanpham");


#line default
#line hidden

#line 5 "C:\Users\Admin\AppData\Local\Temp\1CAF4F21D0414992FE7B26AF3AD46BC7D261\7\DAPM_NHOM2\Ictshop\Views\Home\Index.cshtml"
__o = Html.Action("dtxiaomipartial", "Sanpham");


#line default
#line hidden
}
}
}
